### ISSUE TITLE
Bug passing a list instead of a str

### ISSUE THREAD

**Issue by dumitrescustefan** [adobe/stringlifier#11]
**Describe the bug**

When passing a list to stringlifier, it crashes with:

```
Traceback (most recent call last):
  File "test.py", line 17, in <module>
    x = stringlifier(s.split("/"))
  File "/root/p3.8/lib/python3.8/site-packages/stringlifier/api.py", line 61, in __call__
    new_str, toks = self._extract_tokens(tokens[iBatch], p_ts[iBatch], cutoff=cutoff)
  File "/root/p3.8/lib/python3.8/site-packages/stringlifier/api.py", line 118, in _extract_tokens
    if cls == 'C' and string[ii] in numbers:
```

**Comment by tiberiu44** [comment]
Fixed this and released 1.1.4:

```python
In [1]: from stringlifier.api import Stringlifier                                                                                                                                                                                                                                         

In [2]: s=Stringlifier()                                                                                                                                                                                                                                                                  

In [3]: s(['abc', 'def 12345678'], return_tokens=True)                                                                                                                                                                                                                                    
Out[3]: (['abc', 'def <NUMERIC>'], [[], [('12345678', 4, 11, '<NUMERIC>')]])
```

Hope this helps!
