### ISSUE TITLE
Crash when passing an empty str

### ISSUE THREAD

**Issue by dumitrescustefan** [adobe/stringlifier#12]
**Describe the bug**

Crash when passing None or an empty str ``""`"":

```
Traceback (most recent call last):
  File "test.py", line 20, in <module>
    print(stringlifier(elem)[0])
  File "/root/p3.8/lib/python3.8/site-packages/stringlifier/api.py", line 54, in __call__
    p_ts = self.classifier(tokens)
  File "/root/p3.8/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/p3.8/lib/python3.8/site-packages/stringlifier/modules/stringc2.py", line 142, in forward
    output, _ = self._rnn(hidden)
  File "/root/p3.8/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/p3.8/lib/python3.8/site-packages/torch/nn/modules/rnn.py", line 576, in forward
    result = _VF.lstm(input, hx, self._flat_weights, self.bias, self.num_layers,
RuntimeError: stack expects a non-empty TensorList
```

Expected behaviour: if it's not parsable, return it as-is (even if it is "" or None or an int or an object). Should be as fault-tolerant as possible.

I would only perform processing on elements in the input list if ``isinstance(element, str)``. 
🎸

**Comment by tiberiu44** [comment]
Fixed empty string and released package `1.1.4`. I don't see the point of not failing if the input is `None`, `int`, `bool`, etc.

```python
In [1]: from stringlifier.api import Stringlifier                                                                                                                                                                                                                                         

In [2]: s=Stringlifier()                                                                                                                                                                                                                                                                  

In [3]: s('')                                                                                                                                                                                                                                                                             
Out[3]: ['']

In [4]: s('', return_tokens=True)                                                                                                                                                                                                                                                         
Out[4]: ([''], [])
```
